In [1]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array1
array([1, 2, 3, 4, 5]

SyntaxError: incomplete input (3417913556.py, line 4)

In [2]:
array2 = np.array([9, 8, 7, 6, 5])
array2

NameError: name 'np' is not defined

In [3]:
array3 = array1 + array2
array4 = array3 * 10
array4 / 10

NameError: name 'array1' is not defined

In [4]:
np.empty((10,))
array([5.45083583e-310,

SyntaxError: incomplete input (89333479.py, line 2)

In [5]:
np.arange(0.5,10,0.5)
array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])
np.linspace(-3, 3)

NameError: name 'np' is not defined